create table users(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name varchar not null unique,
    created_at timestamp default CURRENT_TIMESTAMP not null
);

create table chats(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_name varchar not null unique,
    created_at timestamp default CURRENT_TIMESTAMP not null
);

create table messages(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_text TEXT not null,
    created_at timestamp default CURRENT_TIMESTAMP not null,
    chat_id int REFERENCES chats (id),
    user_id int REFERENCES users (id)
);

create table users_chats(
    user_id int REFERENCES users (id),
    chat_id int REFERENCES chats (id)
);

